server {
    listen 80 default;
    client_max_body_size 108M;
    server_name localhost;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /application;
    index index.html index.php;

    # the "via google 1.1 header" turns off default compression. Switch back on!
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # race timeout to avoid race condition with GCP's load balancers
    keepalive_timeout 650;
    keepalive_requests 10000;

    # prettier URLs
    rewrite ^/login/$ /login.php break;
    rewrite ^/logout/$ /logout.php break;
    rewrite ^/wrong/$ /wrong.php break;
    rewrite ^/albums/$ /index.php break;
    rewrite ^/album/(.*)/$ /index.php?album=$1 break;
    # Redirect 404's to home page
    if (!-e $request_filename) {
      rewrite ^.*$ /index.html last;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass photos-app-svc:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}
