apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photo-album

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app: photo-album
